In [13]:
import numpy as np
import csv
import matplotlib.pyplot as plt
import os
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import neighbors
import sklearn
sklearn.__version__

'0.24.1'

In [2]:
classification_folder = "/home/sashank/catkin_ws/src/tactilecloth/classification_data/"
folders=["0cloth_7feb", "1cloth_7feb", "2cloth_7feb"]


In [11]:
# for i in range(15):
#     csv_path = classification_folder + folders[2]+"/"+str(i+1)+"/"+str(i+1)+"_reskin_data.csv"
#     darr = np.loadtxt(csv_path, delimiter= ",")
#     for j in range(darr.shape[0]):
#         if(darr[j][-2] == 2):
#             darr[j][-2] = 3
#         pass
#     np.savetxt(csv_path,darr, delimiter=",")
#     print("done: ",i)
#     pass


done:  0
done:  1
done:  2
done:  3
done:  4
done:  5
done:  6
done:  7
done:  8
done:  9
done:  10
done:  11
done:  12
done:  13
done:  14


In [3]:
classification_folder = "/home/sashank/catkin_ws/src/tactilecloth/classification_data"
folders = ["0cloth_7feb","1cloth_7feb", "2cloth_7feb"]
num_data = 10
train_data = []
test_data_set = [11,12,13,14,15]
for fn in folders:
    for i in range(num_data):
        name = classification_folder+"/"+fn+"/"+str(i+1)+"/"+str(i+1)+"_reskin_data.csv"
        marker_name = classification_folder+"/"+fn+"/"+str(i+1)+"/"+str(i+1)+"_markers.csv"
        nparr = np.loadtxt(name, delimiter=",")
        markerarr = np.loadtxt(marker_name, delimiter=",")
        train_data.append(nparr)
train_data = np.vstack(train_data)
x_train = train_data[:,:-2]
y_train = train_data[:,-2]
scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
test_data_set = np.arange(num_data+1, 16)
test_data = []
for fn in folders:
    for i in test_data_set:
        name = classification_folder+"/"+fn+"/"+str(i)+"/"+str(i)+"_reskin_data.csv"
        marker_name = classification_folder+"/"+fn+"/"+str(i)+"/"+str(i)+"_markers.csv"
        nparr = np.loadtxt(name, delimiter=",")
#         markerarr = np.loadtxt(marker_name, delimiter=",")
#         test_data.append(nparr[int(markerarr[0]*17-20):int(markerarr[0]*17+20),:])
        test_data.append(nparr)
test_data = np.vstack(test_data)
x_test = test_data[:,:-2]
y_test = test_data[:,-2]
x_test = scaler.transform(x_test)

In [4]:
clf = neighbors.KNeighborsClassifier(10, weights="distance")
clf.fit(x_train, y_train)
score = clf.score(x_test, y_test)
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(x_test)
best_cf = confusion_matrix(y_test, y_pred)
print(best_cf)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

[[15490    61     7    16]
 [   70  2283     2     0]
 [  155    30  2338    43]
 [  239   706  1647    16]]


0.7203284670837747

In [8]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state = 0, tol=1e-4)
clf.fit(x_train, y_train)
score = clf.score(x_test, y_test)
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(x_test)
best_cf = confusion_matrix(y_test, y_pred)
print(best_cf)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)


[[15509    59     1     5]
 [   66  2288     0     1]
 [  223     0  1683   660]
 [  295  1360   254   699]]


/home/sashank/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.7228205972233624

In [9]:
x_traim

NameError: name 'x_traim' is not defined

In [20]:
print(np.count_nonzero(y_train[:] == 0))
print(np.count_nonzero(y_train[:] == 1))
print(np.count_nonzero(y_train[:] == 2))
print(np.count_nonzero(y_train[:] == 3))

37280
4579
4902
5160


In [16]:
x_train[:-1]

array([[ 0.71569527,  0.578562  , -0.74943329, ..., -0.02377768,
        -0.54262931, -0.27470228],
       [ 0.62607429,  0.54697783, -0.48475026, ...,  0.03703497,
        -0.47866437, -0.16937415],
       [ 0.68333157,  0.54500486, -0.43831538, ...,  0.12946772,
        -0.45810495, -0.1904389 ],
       ...,
       [ 0.47919541,  0.51243322, -0.74479023, ..., -0.07242586,
        -0.36330144, -0.16235184],
       [ 0.47670599,  0.52329044, -0.49403781, ...,  0.00784364,
        -0.37472334, -0.56962625],
       [ 0.74058947,  0.47097931, -0.81444328, ..., -0.05296538,
        -0.31418555, -0.38003258]])

In [6]:
import pickle
s = pickle.dumps(clf)
clf2 = pickle.loads(s)
clf2.predict(x_test[0:5])

array([0., 0., 0., 0., 0.])

In [10]:
with open("/home/sashank/catkin_ws/src/tactilecloth/scripts/clf.pickle", 'wb') as handle:
    pickle.dump(clf, handle, protocol=2)

NameError: name 'sklearn' is not defined